# Generated by Django 5.2.12 on 2026-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
