# Generated by Django 5.2.12 on 2026-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review_stockalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Repère interne, non affiché sur le site', max_length=200)),
                ('youtube_id', models.CharField(help_text='Identifiant de la vidéo YouTube', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo — Univers visuel',
                'verbose_name_plural': 'Vidéos — Univers visuel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
