# Generated by Django 5.2.12 on 2026-08-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_showcasevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasevideo',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='showcasevideo',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
