# Generated by Django 5.2.12 on 2026-08-18 21:28

import goldenpousso_backend.video_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_showcasevideo_youtube_id_showcasevideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, storage=goldenpousso_backend.video_storage.video_storage, help_text="Optionnel. Si une vidéo est envoyée, c'est elle qui s'affiche sur la carte produit, à la place de la photo. Les photos restent visibles sur la fiche produit.", null=True, upload_to='products/videos/', verbose_name='Vidéo du produit'),
        ),
    ]
