# Generated by Django 5.2.12 on 2026-08-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasevideo',
            name='poster',
            field=models.ImageField(blank=True, help_text='Image fixe montrée avant lecture. Recommandée : format vertical 9/16.', null=True, upload_to='videos/posters/', verbose_name='Affiche'),
        ),
        migrations.AddField(
            model_name='showcasevideo',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Facultatif. Affiche une carte produit cliquable sur la vidéo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_videos', to='store.product', verbose_name='Pièce présentée'),
        ),
    ]
