# Generated by Django 5.2.12 on 2026-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_showcasevideo_poster_showcasevideo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to='products/web/', verbose_name='Variante web'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Photo (original)'),
        ),
    ]
