# Generated by Django 5.2.12 on 2026-08-23 17:16

import store.imaging
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage_display_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelierimage',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to=store.imaging._chemin_variante, verbose_name='Variante web'),
        ),
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to=store.imaging._chemin_variante, verbose_name='Variante web'),
        ),
        migrations.AddField(
            model_name='collection',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to=store.imaging._chemin_variante, verbose_name='Variante web'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to=store.imaging._chemin_variante, verbose_name='Variante web'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display',
            field=models.ImageField(blank=True, help_text='Générée automatiquement. La vider force une régénération.', null=True, upload_to=store.imaging._chemin_variante, verbose_name='Variante web'),
        ),
    ]
