# Generated by Django 5.2.12 on 2026-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_atelierimage_display_category_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelierimage',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': 'Image Atelier', 'verbose_name_plural': 'Images Atelier'},
        ),
        migrations.AddField(
            model_name='atelierimage',
            name='order',
            field=models.IntegerField(default=0, help_text="La première sert la page À propos ; les deux premières la section « Notre savoir-faire » de l'accueil.", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='atelierimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Affichée'),
        ),
    ]
