# Generated by Django 5.2.12 on 2026-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_atelierimage_options_atelierimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelierimage',
            name='emplacement',
            field=models.CharField(choices=[('apropos', 'Page À propos — section « Notre Histoire »'), ('accueil', 'Page d’accueil — section « Notre savoir-faire »')], default='apropos', max_length=10, verbose_name='Emplacement'),
        ),
        migrations.AlterField(
            model_name='atelierimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordre d’affichage à l’intérieur de l’emplacement choisi.', verbose_name='Ordre'),
        ),
    ]
