# Generated by Django 5.2.12 on 2026-08-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_atelierimage_emplacement_alter_atelierimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(help_text="Ne pas modifier : c'est ce qui relie le texte à sa section.", max_length=60, unique=True, verbose_name='Clé technique')),
                ('zone', models.CharField(help_text='Où ce texte apparaît, en clair.', max_length=120, verbose_name='Emplacement')),
                ('surtitre', models.CharField(blank=True, help_text="La petite ligne au-dessus du titre. Laisser vide s'il n'y en a pas.", max_length=120, verbose_name='Sur-titre')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Titre de section',
                'verbose_name_plural': 'Titres de sections',
                'ordering': ['zone'],
            },
        ),
    ]
