# Generated by Django 5.2.12 on 2026-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_textes_sections_initiaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelierimage',
            name='emplacement',
            field=models.CharField(choices=[('apropos', 'Page À propos — section « Notre Histoire »'), ('accueil', 'Page d’accueil — section « Notre savoir-faire »'), ('promotion', 'Page d’accueil — fond de la bande promotionnelle')], default='apropos', max_length=10, verbose_name='Emplacement'),
        ),
    ]
