# Generated by Django 5.2.12 on 2026-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_atelierimage_emplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
