# Generated by Django 5.2.12 on 2026-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_collection_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Le grand mot en tête, par exemple « Promotion ».', max_length=60, verbose_name='Titre')),
                ('offre', models.CharField(help_text="Ce qui motive l'offre, par exemple « Bientôt la Tabaski ».", max_length=80, verbose_name='Occasion')),
                ('accroche', models.CharField(help_text='Le rabais lui-même, par exemple « −15 % sur tous nos articles ».', max_length=80, verbose_name='Offre')),
                ('lien', models.CharField(default='/recherche', help_text='Chemin interne. « /recherche » pour toute la boutique, « /categorie/boubous » pour un seul rayon.', max_length=200, verbose_name='Destination du bouton')),
                ('libelle_lien', models.CharField(default='Voir la boutique', max_length=40, verbose_name='Texte du bouton')),
                ('debut', models.DateField(help_text="Premier jour d'affichage.", verbose_name='Début')),
                ('fin', models.DateField(help_text="Dernier jour d'affichage, inclus.", verbose_name='Fin')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher suspend la campagne sans la supprimer.', verbose_name='Activée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion du hero',
                'verbose_name_plural': 'Promotions du hero',
                'ordering': ['-debut'],
            },
        ),
    ]
