# Generated by Django 5.2.12 on 2026-09-02 10:12

import goldenpousso_backend.video_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_heropromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasevideo',
            name='video',
            field=models.FileField(storage=goldenpousso_backend.video_storage.video_storage, upload_to='videos/'),
        ),
    ]
