# Generated by Django 5.2.12 on 2026-09-02 11:42

import goldenpousso_backend.video_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_showcasevideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasevideo',
            name='video_lien',
            field=models.URLField(blank=True, help_text="Adresse publique du fichier, déposé sur Cloudflare. C'est la façon recommandée : rien ne transite par le site.", max_length=500, verbose_name='Lien de la vidéo'),
        ),
        migrations.AlterField(
            model_name='showcasevideo',
            name='video',
            field=models.FileField(blank=True, storage=goldenpousso_backend.video_storage.video_storage, upload_to='videos/'),
        ),
    ]
