# Generated by Django 5.2.12 on 2026-09-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_showcasevideo_video_lien_alter_showcasevideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
