# Generated by Django 5.2.12 on 2026-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_retirer_vedette_nouveaute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
