# Generated by Django 5.2.12 on 2026-09-15 19:58

from django.db import migrations

# Les avis clients sont retirés du site, front et back, à la demande. Leurs
# titres de section partent avec eux, et celui de « La sélection », retirée
# avec les pièces « Vedette » : plus rien ne les lit.
TITRES_ORPHELINS = ['accueil-avis', 'accueil-selection']


def retirer_titres(apps, schema_editor):
    SectionTexte = apps.get_model('store', 'SectionTexte')
    SectionTexte.objects.filter(cle__in=TITRES_ORPHELINS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_retirer_texte_alternatif'),
    ]

    operations = [
        migrations.RunPython(retirer_titres, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
