# Generated by Django 5.2.12 on 2026-09-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_retirer_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
