# Generated by Django 5.2.12 on 2026-09-15 20:59

import django.db.models.deletion
from django.db import migrations, models


def supprimer_pieces_masquees(apps, schema_editor):
    """Les pièces masquées sont supprimées, à la demande.

    La possibilité de masquer une pièce disparaît : sans cela, les pièces
    masquées réapparaîtraient sur le site. Elles avaient été commandées — d'où
    l'ordre des opérations : la ligne de commande est d'abord détachée de sa
    pièce (SET_NULL, plus haut), et garde son nom, son prix et sa quantité.
    Photos, variantes et alertes de réassort partent avec la pièce (CASCADE).
    """
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(is_active=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_retirer_video_produit'),
    ]

    operations = [
        # 1. Détacher : une ligne de commande ne protège plus sa pièce.
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        # 2. Supprimer les pièces masquées — irréversible.
        migrations.RunPython(supprimer_pieces_masquees, migrations.RunPython.noop),
        # 3. Retirer le champ.
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
