# Generated by Django 5.2.12 on 2026-09-16 15:30

from django.db import migrations, models


def preparation_vers_payee(apps, schema_editor):
    """Plus d'étape « En préparation », à la demande : on vend des vêtements,
    une commande payée part en livraison. Les commandes qui y étaient
    reviennent à « Payée » (clé `confirmed`), l'étape qui la précédait."""
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(status='processing').update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_categories_nom_et_parent'),
    ]

    operations = [
        # Tout paiement passe par PayDunya, à la demande : nouveau choix par
        # défaut. Les anciens moyens restent pour l'historique.
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paydunya', 'PayDunya (carte ou mobile money)'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('free_money', 'Free Money'), ('cash_on_delivery', 'Paiement à la livraison'), ('card', 'Carte bancaire')], default='paydunya', max_length=20),
        ),
        migrations.RunPython(preparation_vers_payee, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Payée'), ('shipped', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
