# Generated by Django 5.2.12 on 2026-09-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_paiement_paydunya_et_statuts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroBanner',
        ),
    ]
