# Generated by Django 5.2.12 on 2026-09-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_retirer_banniere_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtelierImage',
        ),
    ]
