# Generated by Django 5.2.12 on 2026-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_videos_par_lien_uniquement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(help_text="Telle qu'elle s'affiche, par exemple « Pikine Tally Boumack ».", max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(help_text="Dans sa présentation locale, par exemple « 77 751 47 95 ». Le lien d'appel est fabriqué à partir de ce numéro.", max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coordonnées de la boutique',
                'verbose_name_plural': 'Coordonnées de la boutique',
            },
        ),
    ]
